//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.ZakaznikReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZakaznikReference.IZakaznikService")]
    public interface IZakaznikService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakaznikService/Insert", ReplyAction="http://tempuri.org/IZakaznikService/InsertResponse")]
        int Insert(DTO.Zakaznik zakaznik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakaznikService/Insert", ReplyAction="http://tempuri.org/IZakaznikService/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(DTO.Zakaznik zakaznik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakaznikService/Update", ReplyAction="http://tempuri.org/IZakaznikService/UpdateResponse")]
        int Update(DTO.Zakaznik zakaznik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakaznikService/Update", ReplyAction="http://tempuri.org/IZakaznikService/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(DTO.Zakaznik zakaznik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakaznikService/Select", ReplyAction="http://tempuri.org/IZakaznikService/SelectResponse")]
        System.Collections.ObjectModel.Collection<DTO.Zakaznik> Select();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakaznikService/Select", ReplyAction="http://tempuri.org/IZakaznikService/SelectResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<DTO.Zakaznik>> SelectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakaznikService/SelectBy", ReplyAction="http://tempuri.org/IZakaznikService/SelectByResponse")]
        System.Collections.ObjectModel.Collection<DTO.Zakaznik> SelectBy(NullDTO.ZakaznikNull zakaznikNull);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakaznikService/SelectBy", ReplyAction="http://tempuri.org/IZakaznikService/SelectByResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<DTO.Zakaznik>> SelectByAsync(NullDTO.ZakaznikNull zakaznikNull);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakaznikService/Detail", ReplyAction="http://tempuri.org/IZakaznikService/DetailResponse")]
        DTO.Zakaznik Detail(int idZak);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakaznikService/Detail", ReplyAction="http://tempuri.org/IZakaznikService/DetailResponse")]
        System.Threading.Tasks.Task<DTO.Zakaznik> DetailAsync(int idZak);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakaznikService/Delete", ReplyAction="http://tempuri.org/IZakaznikService/DeleteResponse")]
        int Delete(int idZak);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakaznikService/Delete", ReplyAction="http://tempuri.org/IZakaznikService/DeleteResponse")]
        System.Threading.Tasks.Task<int> DeleteAsync(int idZak);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZakaznikServiceChannel : BL.ZakaznikReference.IZakaznikService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZakaznikServiceClient : System.ServiceModel.ClientBase<BL.ZakaznikReference.IZakaznikService>, BL.ZakaznikReference.IZakaznikService {
        
        public ZakaznikServiceClient() {
        }
        
        public ZakaznikServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZakaznikServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZakaznikServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZakaznikServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(DTO.Zakaznik zakaznik) {
            return base.Channel.Insert(zakaznik);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(DTO.Zakaznik zakaznik) {
            return base.Channel.InsertAsync(zakaznik);
        }
        
        public int Update(DTO.Zakaznik zakaznik) {
            return base.Channel.Update(zakaznik);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(DTO.Zakaznik zakaznik) {
            return base.Channel.UpdateAsync(zakaznik);
        }
        
        public System.Collections.ObjectModel.Collection<DTO.Zakaznik> Select() {
            return base.Channel.Select();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<DTO.Zakaznik>> SelectAsync() {
            return base.Channel.SelectAsync();
        }
        
        public System.Collections.ObjectModel.Collection<DTO.Zakaznik> SelectBy(NullDTO.ZakaznikNull zakaznikNull) {
            return base.Channel.SelectBy(zakaznikNull);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<DTO.Zakaznik>> SelectByAsync(NullDTO.ZakaznikNull zakaznikNull) {
            return base.Channel.SelectByAsync(zakaznikNull);
        }
        
        public DTO.Zakaznik Detail(int idZak) {
            return base.Channel.Detail(idZak);
        }
        
        public System.Threading.Tasks.Task<DTO.Zakaznik> DetailAsync(int idZak) {
            return base.Channel.DetailAsync(idZak);
        }
        
        public int Delete(int idZak) {
            return base.Channel.Delete(idZak);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(int idZak) {
            return base.Channel.DeleteAsync(idZak);
        }
    }
}
