//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.RecenzeReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RecenzeReference.IRecenzeService")]
    public interface IRecenzeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecenzeService/Insert", ReplyAction="http://tempuri.org/IRecenzeService/InsertResponse")]
        int Insert(DTO.Recenze recenze);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecenzeService/Insert", ReplyAction="http://tempuri.org/IRecenzeService/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(DTO.Recenze recenze);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecenzeServiceChannel : BL.RecenzeReference.IRecenzeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecenzeServiceClient : System.ServiceModel.ClientBase<BL.RecenzeReference.IRecenzeService>, BL.RecenzeReference.IRecenzeService {
        
        public RecenzeServiceClient() {
        }
        
        public RecenzeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecenzeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecenzeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecenzeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(DTO.Recenze recenze) {
            return base.Channel.Insert(recenze);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(DTO.Recenze recenze) {
            return base.Channel.InsertAsync(recenze);
        }
    }
}
