//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.ObjednavkaReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ObjednavkaReference.IObjednavkaService")]
    public interface IObjednavkaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjednavkaService/Insert", ReplyAction="http://tempuri.org/IObjednavkaService/InsertResponse")]
        int Insert(DTO.Objednavka objednavka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjednavkaService/Insert", ReplyAction="http://tempuri.org/IObjednavkaService/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(DTO.Objednavka objednavka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjednavkaService/Update", ReplyAction="http://tempuri.org/IObjednavkaService/UpdateResponse")]
        int Update(DTO.Objednavka objednavka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjednavkaService/Update", ReplyAction="http://tempuri.org/IObjednavkaService/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(DTO.Objednavka objednavka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjednavkaService/Select", ReplyAction="http://tempuri.org/IObjednavkaService/SelectResponse")]
        System.Collections.ObjectModel.Collection<DTO.Objednavka> Select();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjednavkaService/Select", ReplyAction="http://tempuri.org/IObjednavkaService/SelectResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<DTO.Objednavka>> SelectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjednavkaService/SelectBy", ReplyAction="http://tempuri.org/IObjednavkaService/SelectByResponse")]
        System.Collections.ObjectModel.Collection<DTO.Objednavka> SelectBy(NullDTO.ObjednavkaNull objednavkaNull);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjednavkaService/SelectBy", ReplyAction="http://tempuri.org/IObjednavkaService/SelectByResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<DTO.Objednavka>> SelectByAsync(NullDTO.ObjednavkaNull objednavkaNull);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjednavkaService/Detail", ReplyAction="http://tempuri.org/IObjednavkaService/DetailResponse")]
        DTO.Objednavka Detail(int idObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjednavkaService/Detail", ReplyAction="http://tempuri.org/IObjednavkaService/DetailResponse")]
        System.Threading.Tasks.Task<DTO.Objednavka> DetailAsync(int idObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjednavkaService/Delete", ReplyAction="http://tempuri.org/IObjednavkaService/DeleteResponse")]
        int Delete(int idObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjednavkaService/Delete", ReplyAction="http://tempuri.org/IObjednavkaService/DeleteResponse")]
        System.Threading.Tasks.Task<int> DeleteAsync(int idObj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IObjednavkaServiceChannel : BL.ObjednavkaReference.IObjednavkaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObjednavkaServiceClient : System.ServiceModel.ClientBase<BL.ObjednavkaReference.IObjednavkaService>, BL.ObjednavkaReference.IObjednavkaService {
        
        public ObjednavkaServiceClient() {
        }
        
        public ObjednavkaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ObjednavkaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjednavkaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjednavkaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(DTO.Objednavka objednavka) {
            return base.Channel.Insert(objednavka);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(DTO.Objednavka objednavka) {
            return base.Channel.InsertAsync(objednavka);
        }
        
        public int Update(DTO.Objednavka objednavka) {
            return base.Channel.Update(objednavka);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(DTO.Objednavka objednavka) {
            return base.Channel.UpdateAsync(objednavka);
        }
        
        public System.Collections.ObjectModel.Collection<DTO.Objednavka> Select() {
            return base.Channel.Select();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<DTO.Objednavka>> SelectAsync() {
            return base.Channel.SelectAsync();
        }
        
        public System.Collections.ObjectModel.Collection<DTO.Objednavka> SelectBy(NullDTO.ObjednavkaNull objednavkaNull) {
            return base.Channel.SelectBy(objednavkaNull);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<DTO.Objednavka>> SelectByAsync(NullDTO.ObjednavkaNull objednavkaNull) {
            return base.Channel.SelectByAsync(objednavkaNull);
        }
        
        public DTO.Objednavka Detail(int idObj) {
            return base.Channel.Detail(idObj);
        }
        
        public System.Threading.Tasks.Task<DTO.Objednavka> DetailAsync(int idObj) {
            return base.Channel.DetailAsync(idObj);
        }
        
        public int Delete(int idObj) {
            return base.Channel.Delete(idObj);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(int idObj) {
            return base.Channel.DeleteAsync(idObj);
        }
    }
}
